language: objective-c
matrix:
  include:
  - osx_image: xcode10.2
    env: XCODE=10.2
  - osx_image: xcode10.1
    env: XCODE=10.1
  - osx_image: xcode10
    env: XCODE=10
  - osx_image: xcode9.4
    env: XCODE=9.4
  - osx_image: xcode9.3
    env: XCODE=9.3
  - osx_image: xcode9.2
    env: XCODE=9.2
  - osx_image: xcode9.1
    env: XCODE=9.1
  - osx_image: xcode9
    env: XCODE=9

cache:
  directories:
  - Carthage
  - Inspector/node_modules

install:
  - wget https://download.microsoft.com/download/D/0/4/D04C5489-278D-4C11-9BD3-6128472A7626/dotnet-sdk-2.1.301-osx-x64.pkg -O ~/dotnet-sdk-2.1.301-osx-gs-x64.pkg -nv
  - sudo installer -pkg ~/dotnet-sdk-2.1.301-osx-gs-x64.pkg -target /
  - PATH="/usr/local/share/dotnet/:$PATH"
  - dotnet --version

script:
  - ./Scripts/bootstrap.sh
  - ./signing/add-key.sh
  - security find-identity -v -p codesigning
  - ./build-ipa.sh
  - cd Quamotion.WebDriverAgent
  - cp ../out/WebDriverAgent-$TRAVIS_BUILD_NUMBER.zip ./WebDriverAgent.zip
  - dotnet build -c Release /p:VersionSuffix=r$TRAVIS_BUILD_NUMBER-xcode-$XCODE
  - dotnet pack -c Release /p:VersionSuffix=r$TRAVIS_BUILD_NUMBER-xcode-$XCODE
  - dotnet nuget push bin/Release/Quamotion.WebDriverAgent.1.0.0-r$TRAVIS_BUILD_NUMBER-xcode-$XCODE.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_TOKEN
